{
    "url": "https://raw.githubusercontent.com/NickRossoABT/xss-vulnerability-playground/development/payload.json",
    "urls": [
        {
            "url": "https://raw.githubusercontent.com/NickRossoABT/xss-vulnerability-playground/development/payload.json",
            "name": "XSS-exploit"
        }
    ]
}        