{
  "openapi": "3.0.1",
  "info": {
    "title": "Nicks Custom Swagger UI",
    "version": "v1"
  },
  "paths": {
    "/api/Zendesk/Token": {
      "post": {
        "tags": [
          "Zendesk"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Payload"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/Payload"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/Payload"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                }
              },
              "application/json": {
                "schema": {
                  "type": "string"
                }
              },
              "text/json": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },

  },
  "components": {
    "schemas": {
      "Payload": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "nullable": true
          },
          "email": {
            "type": "string",
            "nullable": true
          },
          "iat": {
            "type": "integer",
            "format": "int64"
          },
          "jti": {
            "type": "integer",
            "format": "int32"
          }
        },
        "additionalProperties": false
      },
      "SkillAgent": {
        "type": "object",
        "properties": {
          "user_id": {
            "type": "integer",
            "format": "int64"
          },
          "group_id": {
            "type": "integer",
            "format": "int64"
          }
        },
        "additionalProperties": false
      },
      "GroupMembership": {
        "type": "object",
        "properties": {
          "group_membership": {
            "$ref": "#/components/schemas/SkillAgent"
          }
        },
        "additionalProperties": false
      }
    }
  }
}